# @package _global_
# Shared experiment scaffold for stage-1 dataset generation.
# Use with: python create_dataset.py +exp=base +exp/phase=main +exp/method=<...> +exp/budget/<...>=<...> +exp/seed=<...>

experiment:
  id: thesis_sm4_v1
  phase: unset
  method: unset
  budget: unset
  seed: unset

# Write each run into a deterministic, isolated root to avoid dataset_vN race conditions
# when running many jobs in parallel.
dirs:
  dataset_dir: ${hydra:runtime.cwd}/outputs/experiments/${experiment.id}/${experiment.phase}/${experiment.method}/${experiment.budget}/${experiment.seed}/data

# QBC logging defaults. LHS method config disables them.
qbc_enable_logging: true
qbc_run_dir: ${hydra:runtime.cwd}/outputs/experiments/${experiment.id}/${experiment.phase}/${experiment.method}/${experiment.budget}/${experiment.seed}/qbc
qbc_resume_from_round: -1
qbc_resume_stage: next_round
