"""Shared plotting utilities for thesis and result visualizations."""

from .results_helpers import (
    aggregate_mean_sem,
    artifact_path,
    ensure_repo_root_on_path,
    epoch_metrics_path,
    eval_metric,
    load_json,
    mean_sem_text,
    metrics_json_path,
    read_csv_if_exists,
    read_epoch_metrics,
    run_dir,
    save_and_show,
    sem,
    split_metric,
    timings_json_path,
)
from .thesis_style import (
    DTU_COLORS,
    THESIS_BUDGET_COLORS,
    THESIS_METHOD_COLORS,
    THESIS_STYLE,
    adjust_scatter_labels,
    log_minor_grid,
    save_figure,
    set_thesis_style,
)

__all__ = [
    "DTU_COLORS",
    "THESIS_BUDGET_COLORS",
    "THESIS_METHOD_COLORS",
    "THESIS_STYLE",
    "adjust_scatter_labels",
    "log_minor_grid",
    "aggregate_mean_sem",
    "artifact_path",
    "ensure_repo_root_on_path",
    "epoch_metrics_path",
    "eval_metric",
    "load_json",
    "mean_sem_text",
    "metrics_json_path",
    "read_csv_if_exists",
    "read_epoch_metrics",
    "run_dir",
    "save_figure",
    "save_and_show",
    "set_thesis_style",
    "sem",
    "split_metric",
    "timings_json_path",
]
